"""Work 5A 最小Review Task ContractのRuntime package。

正本設計：docs/design/2026-08-05-work-4-first-review-task-contract-design-proposal.md
承認：DEC-WORK4-FIRST-REVIEW-CONTRACT-DESIGN-001

一Contract type、一Compiler version、`new_development / fresh`だけを扱う。
LLM、外部送信、Git write、CIを使わない。`tools/bootstrap/`は参照せず、昇格もしない。
"""

from tools.task_contract.contract import (
    BOUND_REQUIREMENT_IDS,
    COMPILE_GATE_REASONS,
    CONTINUATION_CLASSES,
    CONTRACT_APPROVAL_OWNER,
    CONTRACT_V2_REQUIRED_EDGES,
    DEFAULT_REVIEW_OWNERS,
    DEFINITION_CHALLENGE_OWNER,
    ORIGIN_CLASSES,
    PLAN_VIEWS,
    REQUIREMENT_OBLIGATIONS,
    REQUIREMENT_RECEIVERS,
    SEVERITY_CLASSES,
    bind_requirements,
    build_review_task_contract,
    check_requirement_coverage,
    compile_contract,
    compile_gate_reason,
)
from tools.task_contract.definition_challenge import (
    CONTRACT_APPROVAL_DECISIONS,
    DEFINITION_CHECKS,
    DEFINITION_SEVERITY_CLASSES,
    DEFINITION_VERDICT_STATUSES,
    FORBIDDEN_CAPABILITIES,
    STAGE_CONFUSION_KINDS,
    build_contract_approval,
    build_definition_challenge_material_set,
    run_definition_challenge,
)
from tools.task_contract.execution import (
    CONTRACT_V2_EDGE_ORDER,
    FINDING_KINDS,
    FINDING_ORIGIN_ROUTES,
    PROVENANCE_EDGE_ORDER,
    accept_artifact,
    acquire_permit,
    active_leaf_count,
    assert_context_fresh,
    build_context_manifest,
    evaluate_conformance,
    evaluate_final_challenge,
    new_workflow_state,
    read_source_snapshot,
    record_human_decision,
    release_permit,
    provenance_node_roles,
    run_stub_reviewer,
    validate_provenance_verdict,
    verify_provenance,
)
from tools.task_contract.identity import (
    CONTRACT_SECTIONS,
    RECORD_KINDS,
    STOP_CODES,
    ContractError,
    record_ref,
    validate_record,
)

__all__ = [
    "BOUND_REQUIREMENT_IDS",
    "COMPILE_GATE_REASONS",
    "CONTINUATION_CLASSES",
    "CONTRACT_APPROVAL_DECISIONS",
    "CONTRACT_APPROVAL_OWNER",
    "CONTRACT_SECTIONS",
    "CONTRACT_V2_EDGE_ORDER",
    "CONTRACT_V2_REQUIRED_EDGES",
    "ContractError",
    "DEFAULT_REVIEW_OWNERS",
    "DEFINITION_CHALLENGE_OWNER",
    "DEFINITION_CHECKS",
    "DEFINITION_SEVERITY_CLASSES",
    "DEFINITION_VERDICT_STATUSES",
    "FINDING_KINDS",
    "FINDING_ORIGIN_ROUTES",
    "FORBIDDEN_CAPABILITIES",
    "ORIGIN_CLASSES",
    "PLAN_VIEWS",
    "PROVENANCE_EDGE_ORDER",
    "RECORD_KINDS",
    "REQUIREMENT_OBLIGATIONS",
    "REQUIREMENT_RECEIVERS",
    "SEVERITY_CLASSES",
    "STAGE_CONFUSION_KINDS",
    "STOP_CODES",
    "accept_artifact",
    "acquire_permit",
    "active_leaf_count",
    "assert_context_fresh",
    "bind_requirements",
    "build_context_manifest",
    "build_contract_approval",
    "build_definition_challenge_material_set",
    "build_review_task_contract",
    "check_requirement_coverage",
    "compile_contract",
    "compile_gate_reason",
    "evaluate_conformance",
    "evaluate_final_challenge",
    "new_workflow_state",
    "provenance_node_roles",
    "read_source_snapshot",
    "record_human_decision",
    "record_ref",
    "release_permit",
    "run_definition_challenge",
    "run_stub_reviewer",
    "validate_provenance_verdict",
    "validate_record",
    "verify_provenance",
]
